[package]
name = "norseline-rs"
version = "0.1.0"
authors = ["damccull <damccull+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
dotenv = "0.15.0"
reqwest = "0.11.3"
futures = "0.3.15"
rand = "0.8.3"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"

[dependencies.ed25519-dalek]
version = "1"
